home-assistant/mp-rest/url: ${HOME_ASSISTANT_URL}

hafacade:
  home-assistant-auth-token: ${HOME_ASSISTANT_AUTH_TOKEN}
  calendar:
    entity-name: calendar.familienkalender
    max-events-today: 5
    max-events-tomorrow: 5
  waste-bin-calendar:
    entity-name: calendar.abfuhrkalender_2020
    bygone-days: 2
    days-to-come: 35
