home-assistant/mp-rest/url: ${HOME_ASSISTANT_URL}

hafacade:
  home-assistant-auth-token: ${HOME_ASSISTANT_AUTH_TOKEN}
  calendar:
    entity-name: calendar.familienkalender
    max-events-today: 5
    max-events-tomorrow: 5
